### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by mike632t** [davidly/ntvdm#1]
I don't suppose you have thought about porting this to Linux (obviously command line only, no screen orientated stuff).

(It is probably not worth the effort, but I was just curious!)

**Comment by davidly** [comment]
Yes, I've thought about it a few times. That actually worked in the original version exactly like you describe. But then for the screen and keyboard pieces it was just so much easier to build on Windows.  It seems like a worthwhile project to get command line working again on Linux!

**Comment by mike632t** [comment]
That would be amazing!

**Comment by davidly** [comment]
I've added initial Linux support. There are caveats in the readme, but it generally works on my Ubuntu machine.

**Comment by davidly** [comment]
There's more work to do, but it generally works, so I'm going to close this issue.

**Comment by mike632t** [comment]
That is AWESOME - I'll give it a road test and let you know how I get on!
