### ISSUE TITLE
Success

### ISSUE THREAD

**Issue by mike632t** [davidly/ntvdm#3]
Not really an issue but I thought you would be interested to know that `ntdvm` compiled and ran successfully (well was able to run TURBO.COM) on Debian 12 (Bookworm) using gcc 12.2.0 on i686 (32-bit) and amd64 (64-bit) hardware.

Nice job!

**Comment by davidly** [comment]
Sweet! Thank you for doing this and letting me know. I was worried there would be issues on other platforms.

**Comment by mike632t** [comment]
I can check a few others and let you know the results if you want?

**Comment by davidly** [comment]
That'd be fantastic, thanks!

**Comment by davidly** [comment]
Closing this item.
