### ISSUE TITLE
Can't break out of a program using Ctrl-C

### ISSUE THREAD

**Issue by mike632t** [davidly/ntvdm#5]
Can't break out of a program using Ctrl-C (or Ctrl-Z).

If prompted to enter a file name,  should entering Ctrl-C terminate the program? 

Unfortunately it seems to be ignored.
```
$ ../ntvdm -u -d -h CL.EXE SIEVE.C
Microsoft C Compiler  Version 3.00
(C)Copyright Microsoft Corp 1984 1985
SIEVE.C

Microsoft 8086 Object Linker
Version 3.01 (C) Copyright Microsoft Corp 1983, 1984, 1985

Object Modules [.OBJ]: SIEVE.OBJ 
Run File [SIEVE.EXE]: SIEVE.EXE/NOI
List File [NUL.MAP]: NUL
Libraries [.LIB]: ;
Cannot find library: EM.LIB
Enter new file spec: ^C
```
I have not been able to test in a DOS environment yet so I can't be sure if this was supposed to happen.  (I do still have a real DOS machine somewhere!).

Generally having far too much 'fun' messing about to see what works.  I just wish I was the same age as the last time I used some of this software!

**Comment by davidly** [comment]
Good issue! ^C handling is not working -- I'll get to this.

**Comment by davidly** [comment]
should be fixed now for this app. Some apps override the ^c int23 vector and some don't.
