### ISSUE TITLE
Output buffers not flushed on Linux Console 

### ISSUE THREAD

**Issue by mike632t** [davidly/ntvdm#8]
Using commit 94f38de.

Attempting to compile `TP.BAS` from the command line using `BC.EXE` appears to hang after displaying the copyright message.

```
/DOS/UTL$ ../ntvdm BC.EXE
Microsoft (R) BASIC Compiler Version 7.10
Copyright (C) Microsoft Corporation 1982-1990. All rights reserved.
```
However, it hasn't really hung but is just waiting for the name of the source file to be entered.  No prompt is shown on the console since although it has been printed by `ntvdm` file buffer hasn't been flushed so nothing shows on the console...

Entering `TP.BAS` and pressing <RETURN> twice results in the following, with the output being displayed as `ntvdm` exits.
```
/DOS/UTL$ ../ntvdm BC.EXE
Microsoft (R) BASIC Compiler Version 7.10
Copyright (C) Microsoft Corporation 1982-1990. All rights reserved.
TP.BAS



45684 Bytes Available
45620 Bytes Free

    0 Warning Error(s)
    0 Severe  Error(s)

Source Filename [.bas]: 
Object Filename [TP.obj]: 
Source Listing [nul.lst]: /DOS/UTL$ 
```

**Comment by davidly** [comment]
I've check in a work-around, though it may not be one you like :)
The fix is to force 80x25 mode by default for BC.EXE, since it uses normal console out for the banner/copyright then writes directly to video memory for the input file prompts. You can work around this with the current version using -C to force 80x25 mode.

I don't have plans to detect writes to video memory that may be console-mode worthy since this is one of the only apps that mixes and matches. Plus I always put all the input files on the command-line and don't use interactive mode :)

**Comment by mike632t** [comment]
How weird, but I suppose it makes sense if the same code is being used to update the display in the IDE environment.

I can't decide if the workaround is a good idea or not!   (Does `-c` over ride it?).  

The more I discover about the strange behaviour of some of these (ordinary) programs the more amazed I am that you managed to get anything to work as well as you have!

As an aside using uppercase folder names I was able to load and save files using QBX.EXE but being able to set the location of `C:\` as a command line parameter would be a big plus on Linux (and possibly Windows)...

**Comment by davidly** [comment]
Yes, -c will override BC.EXE going into 80x25 mode. But then you can't use BC in interactive mode without invisible prompts.

I find using command-line arguments with BC is just easier. For example, with TP.BAS:

../ntvdm -c -u BC.EXE tp.bas tp.obj tp.lst /O
../ntvdm -c -u LINK.EXE tp,,tp,,nul.def

**Comment by mike632t** [comment]
Thought I'd added a new comment to the effect that the linker had the same problem but can't see it this morning, if you do ignore it!! (the right way to solve the problem is to probably to use `-C`).  I'll update the README with some examples later and put one of my paragraphs in the right place!
